[simulation]
  name = "reconnection"
  engine = "srpic"
  runtime = 10.0

[grid]
  resolution = [2048, 1024]
  extent = [[-1.0, 1.0], [-0.5, 0.5]]

  [grid.metric]
    metric = "minkowski"

  [grid.boundaries]
    fields = [["PERIODIC"], ["CUSTOM"]]
    particles = [["PERIODIC"], ["CUSTOM"]]
    
[scales]
  larmor0 = 2e-4
  skindepth0 = 2e-3

[algorithms]
  current_filters = 8

  [algorithms.timestep]
    CFL = 0.5

[particles]
  ppc0 = 5.0

  [[particles.species]]
  label = "e-"
  mass = 1.0
  charge = -1.0
  maxnpart = 1e8

  [[particles.species]]
  label = "e+"
  mass = 1.0
  charge = 1.0
  maxnpart = 1e8

[setup]
  Bmag = 1.0
  width = 0.01
  
[output]
  fields = ["N_1", "N_2", "E", "B", "J"]
  format = "hdf5"
  interval_time = 0.1
