[simulation]
  name = "shock"
  engine = "srpic"
  runtime = 100.0

[grid]
  resolution = [2048, 128]
  extent = [[0.0, 10.0], [-0.3125, 0.3125]]

  [grid.metric]
    metric = "minkowski"

  [grid.boundaries]
    fields = [["CONDUCTOR", "ABSORB"], ["PERIODIC"]]
    particles = [["REFLECT", "ABSORB"], ["PERIODIC"]]
    
[scales]
  larmor0 = 1e-2
  skindepth0 = 1e-3

[algorithms]
  current_filters = 4

  [algorithms.timestep]
    CFL = 0.5

[particles]
  ppc0 = 4.0

  [[particles.species]]
  label = "e-"
  mass = 1.0
  charge = -1.0
  maxnpart = 1e7

  [[particles.species]]
  label = "e+"
  mass = 1.0
  charge = 1.0
  maxnpart = 1e7

[setup]
  drift_ux = -0.1
  temperature = 0.01

[output]
  fields = ["N_1", "N_2", "E", "B", "J"]
  format = "hdf5"
  interval_time = 0.1
