[simulation]
title   = "DepositGR"
runtime = 100.0

[domain]
qsph_r0     = 0.0
qsph_h      = 0.0
a           = 0.95
sph_rabsorb = 19.0
resolution  = [512, 512]
extent      = [0.8, 20.0]
boundaries  = [["OPEN", "ABSORB"], ["AXIS"]]

[algorithm]
CFL             = 0.5
current_filters = 4

[units]
ppc0       = 4.0
larmor0    = 2e-3
skindepth0 = 0.1

[particles]
n_species    = 2

[species_1]
label    = "e-"
mass     = 1.0
charge   = -1.0
maxnpart = 1e2

[species_2]
label    = "e+"
mass     = 1.0
charge   = 1.0
maxnpart = 1e2

[problem]
r0   = [5.000, 15.0, 18.0, 4.0, 12.0]
th0  = [1.5707963268, 0.7853981634, 2.3561944902, 0.1, 3.0415926536]
ph0  = [0.0, 0.0, 0.0, 0.0, 0.0]
ur0  = [10.0, 10.0, 10.0, 10.0, 10.0]
uth0 = [1.0, 1.0, 1.0, -1.0, 1.0]

[output]
fields        = ["D"]
particles     = ["X"]
format        = "HDF5"
interval_time = 0.05