[simulation]
  name = "langmuir"
  engine = "srpic"
  runtime = 0.1

[grid]
  resolution = [2048]
  extent = [[0.0, 1.0]]

  [grid.metric]
    metric = "minkowski"

  [grid.boundaries]
    fields = [["PERIODIC"]]
    particles = [["PERIODIC"]]
    
[scales]
  larmor0 = 0.1
  skindepth0 = 0.01

[algorithms]
  current_filters = 8

  [algorithms.timestep]
    CFL = 0.5

[particles]
  ppc0 = 14.0

  [[particles.species]]
  label = "e-"
  mass = 1.0
  charge = -1.0
  maxnpart = 1e6

  [[particles.species]]
  label = "e+"
  mass = 1.0
  charge = 1.0
  maxnpart = 1e6

[setup]
  vmax = 0.1
  nx1 = 4
  
[output]
  fields = ["Rho", "E"]
  format = "hdf5"
  interval_time = 0.001

[diagnostics]
  colored_stdout = true