[simulation]
  name = "langmuir"
  engine = "srpic"
  runtime = 0.1

[grid]
  resolution = [256, 64]
  extent = [[0.0, 1.0], [0.0, 0.25]]

  [grid.metric]
    metric = "minkowski"

  [grid.boundaries]
    fields = [["PERIODIC"], ["PERIODIC"]]
    particles = [["PERIODIC"], ["PERIODIC"]]
    
[scales]
  larmor0 = 0.1
  skindepth0 = 0.01

[algorithms]
  current_filters = 0

  [algorithms.timestep]
    CFL = 0.5

  [algorithms.toggles]
    deposit = true

[particles]
  ppc0 = 14.0

  [[particles.species]]
  label = "e-"
  mass = 1.0
  charge = -1.0
  maxnpart = 1e7

  [[particles.species]]
  label = "e+"
  mass = 1.0
  charge = 1.0
  maxnpart = 1e7

[setup]
  vmax = 0.1
  nx1 = 4
  nx2 = 2
  
[output]
  fields = ["Rho", "E"]
  format = "hdf5"
  interval_time = 0.001

[diagnostics]
  colored_stdout = true