[simulation]
title           = "spherical single particle"
runtime         = 0.1

[domain]
qsph_r0         = -10.0
qsph_h          = 0.6
sph_rabsorb     = 18.0
resolution      = [2048, 2048]
extent          = [1.0, 20.0]
boundaries      = ["USER", "USER"]

[algorithm]
CFL             = 0.95
correction      = 1.0
fieldsolver_ON  = true
deposit_ON      = true
current_filters = 4

[units]
ppc0            = 1.0
larmor0         = 0.1
skindepth0      = 1.0

[particles]
n_species       = 2

[species_1]
label           = "electron"
mass            = 1.0
charge          = -1.0
maxnpart        = 1e2

[species_2]
label           = "positron"
mass            = 1.0
charge          = 1.0
maxnpart        = 1e2

[species_3]
label           = "ion"
mass            = 5.0
charge          = 1.0
maxnpart        = 1e2

[species_4]
label           = "photon"
mass            = 0.0
charge          = 0.0
maxnpart        = 1e2

[visualization]
fields          = ["Er", "Etheta", "Ephi", "Br", "Btheta", "Bphi", "Jr", "Jtheta", "Jphi"]

[output]
format          = "disabled"
# interval        = 1

[problem]