[simulation]
title           = "Boris example"
runtime         = 0.1

[domain]
resolution      = [256, 256]
extent          = [-2.0, 2.0, -2.0, 2.0]
boundaries      = ["PERIODIC", "PERIODIC"]

[algorithm]
CFL             = 0.5
correction      = 1.0
#fieldsolver_ON  = true
deposit_ON      = true
current_filters = 2

[units]
ppc0            = 1.0
larmor0         = 0.1
skindepth0      = 10.0

[particles]
n_species       = 2

[species_1]
label           = "electron"
mass            = 1.0
charge          = -1.0
maxnpart        = 1e2
pusher          = "Boris"

[species_2]
label           = "positron"
mass            = 1.0
charge          = 1.0
maxnpart        = 1e2
pusher          = "Boris"

[species_3]
label           = "ion"
mass            = 2.0
charge          = 1.0
maxnpart        = 1e2
pusher          = "Boris"

[species_4]
label           = "photon"
mass            = 0.0
charge          = 0.0
maxnpart        = 1e2
pusher          = "Photon"

[problem]

[visualization]
fields          = ["Bx", "By", "Bz", "Ex", "Ey", "Ez", "Jx", "Jy", "Jz"]
