[simulation]
title   = "Deposit example"
runtime = 0.1

[domain]
resolution = [128, 128]
extent     = [-0.5, 0.5, -0.5, 0.5]
boundaries = [["PERIODIC"], ["PERIODIC"]]

[algorithm]
CFL        = 0.5
correction = 1.0

[units]
ppc0       = 10.0
larmor0    = 1.0
skindepth0 = 20.0

[particles]
n_species = 2

[species_1]
label    = "electron"
mass     = 1.0
charge   = -1.0
maxnpart = 1e2
pusher   = "Boris"

[species_2]
label    = "positron"
mass     = 20.0
charge   = 1.0
maxnpart = 1e2
pusher   = "Boris"

[problem]

[output]
fields = ["B", "E", "J"]
