[simulation]
title   = "Langmuir"
runtime = 100.0

[domain]
resolution = [512, 512]
extent     = [-1.0, 1.0, -1.0, 1.0]
boundaries = [["PERIODIC"], ["PERIODIC"]]

[algorithm]
CFL             = 0.9
correction      = 1.0
fieldsolver_ON  = true
deposit_ON      = true
current_filters = 4

[units]
ppc0       = 10.0
larmor0    = 0.1
skindepth0 = 0.1

[particles]
n_species = 2

[species_1]
label    = "e-"
mass     = 1.0
charge   = -1.0
maxnpart = 1e7
pusher   = "Boris"

[species_2]
label    = "e+"
mass     = 1.0
charge   = 1.0
maxnpart = 1e7
pusher   = "None"

[visualization]
fields        = ["Ex", "Rho_1"]
fields_stride = 1

# [output]
# format          = <string: { disabled, csv }>
# interval        = <int>

[problem]
amplitude   = 1e-2
temperature = 1e-6
nx          = 2
