[simulation]
title   = "Magnetosphere"
runtime = 50.0

[domain]
qsph_r0     = 0.0
qsph_h      = 0.25
sph_rabsorb = 4.5
resolution  = [512, 512]
extent      = [1.0, 5.0]
boundaries  = ["USER", "ABSORB"]

[algorithm]
CFL             = 0.5
correction      = 1.0
current_filters = 8

[units]
ppc0       = 10.0
larmor0    = 1e-4
skindepth0 = 0.05

[particles]
n_species = 2

[species_1]
label    = "e-"
mass     = 1.0
charge   = -1.0
maxnpart = 1e8
pusher   = "BORIS"

[species_2]
label    = "e+"
mass     = 1.0
charge   = 1.0
maxnpart = 1e8
pusher   = "BORIS"

[problem]
bsurf        = 1.0
spin_omega   = 0.02
inj_rmax     = 1.5
inj_fraction = 0.1
inj_maxDens  = 5.0
field_mode   = 1    # 1 = Monopole, 2 = Dipole

[visualization]
fields        = ["density", "Br", "Btheta", "Bphi", "Er", "Etheta", "Ephi", "Jr", "Jphi"]
fields_stride = 4

[output]
format   = "disabled"
interval = 5
