[simulation]
title   = "Magnetosphere"
runtime = 50.0

[domain]
qsph_r0     = 0.0
qsph_h      = 0.001
sph_rabsorb = 4.5
resolution  = [1024, 1024]
extent      = [1.0, 5.0]
boundaries  = ["USER", "ABSORB"]

[algorithm]
CFL             = 0.5
correction      = 1.0
current_filters = 4

[units]
ppc0       = 4.0
larmor0    = 2e-3
skindepth0 = 0.1

[particles]
n_species = 2

[species_1]
label    = "e-"
mass     = 1.0
charge   = -1.0
maxnpart = 1e8
pusher   = "Boris"

[species_2]
label    = "e+"
mass     = 1.0
charge   = 1.0
maxnpart = 1e8
pusher   = "Boris"

[problem]
bsurf        = 1.0
spin_omega   = 0.1
spinup_time  = 1.0
inj_rmax     = 1.2
inj_thmin    = 1e-2
inj_fraction = 0.1
inj_maxDens  = 5.0
field_mode   = 1    # 1 = Monopole, 2 = Dipole
u_kick       = 0.5

[visualization]
fields        = ["mass_density", "Br", "Btheta", "Bphi", "Er", "Etheta", "Ephi", "Jr", "Jphi"]
#fields_stride = 8
fields_stride = 4

[output]
fields        = ["mass_density", "Br", "Btheta", "Bphi", "Er", "Etheta", "Ephi", "Jr", "Jphi"]
format   = "HDF5"
interval = 100
