[simulation]
title   = "Monopole-1"
runtime = 50.0

[domain]
qsph_r0     = 0.0
qsph_h      = 0.25
sph_rabsorb = 4.5
resolution  = [256, 257]
extent      = [1.0, 5.0]
boundaries  = ["USER", "ABSORB"]

[algorithm]
CFL             = 0.5
correction      = 1.0
current_filters = 0

[units]
ppc0       = 10.0
larmor0    = 1e-4
skindepth0 = 0.025

[particles]
n_species = 2

[species_1]
label    = "e-"
mass     = 1.0
charge   = -1.0
maxnpart = 5e7
pusher   = "BORIS"

[species_2]
label    = "e+"
mass     = 1.0
charge   = 1.0
maxnpart = 5e7
pusher   = "BORIS"

[problem]
spin_omega   = 0.25
buff_cells   = 10
inj_rmax     = 1.5
inj_fraction = 0.1

[visualization]
fields        = ["density", "Br", "Btheta", "Bphi", "Er", "Etheta", "Ephi", "Jr", "Jtheta"]
fields_stride = 1

[output]
format   = "disabled"
interval = 5
