[simulation]
title   = "Monopole-1"
runtime = 0.1

[domain]
qsph_r0     = 0.0
qsph_h      = 0.25
sph_rabsorb = 4.5
resolution  = [256, 128]
extent      = [1.0, 5.0]
boundaries  = ["USER", "USER"]

[algorithm]
CFL             = 0.45
correction      = 1.0
current_filters = 0

[units]
ppc0       = 10.0
larmor0    = 1e-4
skindepth0 = 0.02

[particles]
n_species = 2

[species_1]
label    = "e-"
mass     = 1.0
charge   = -1.0
maxnpart = 5e7
pusher   = "BORIS"

[species_2]
label    = "e+"
mass     = 1.0
charge   = 1.0
maxnpart = 5e7
pusher   = "BORIS"

[problem]
spinup_time  = 0.25
omega_max    = 0.25
inj_rmax     = 1.1
inj_maxEdotB = 0
inj_fraction = 0.1

[visualization]
fields        = ["density", "Br", "Btheta", "Bphi", "Er", "Etheta", "Ephi", "Jr", "Jtheta"]
fields_stride = 1
