[simulation]
title   = "Monopole"
runtime = 0.1

[domain]
qsph_r0     = -5.0
qsph_h      = 0.5
sph_rabsorb = 8.0
resolution  = [256, 128]
extent      = [1.0, 10.0]
boundaries  = ["USER", "USER"]

[algorithm]
CFL        = 0.9
correction = 1.0
current_filters = 4

[units]
ppc0       = 10.0
larmor0    = 0.01
skindepth0 = 1.0

[particles]
n_species = 2

[species_1]
label    = "e-"
mass     = 1.0
charge   = -1.0
maxnpart = 5e7
pusher   = "BORIS"

[species_2]
label    = "e+"
mass     = 1.0
charge   = 1.0
maxnpart = 5e7
pusher   = "BORIS"

[problem]
spinup_time = 5.0
omega_max   = 0.25

[visualization]
fields        = ["density", "Br", "Btheta", "Bphi", "Er", "Etheta", "Ephi"]
fields_stride = 1
