[simulation]
title           = "Boris example"
runtime         = 0.1

[domain]
resolution      = [128, 128]
extent          = [-1.0, 1.0, -1.0, 1.0]
boundaries      = ["PERIODIC", "PERIODIC"]

[algorithm]
CFL             = 0.9
correction      = 1.0
fieldsolver_ON  = false
deposit_ON      = false
current_filters = 0

[units]
ppc0            = 1.0
larmor0         = 0.04
skindepth0      = 0.04

[particles]
n_species       = 1

[species_1]
label           = "electron"
mass            = 1.0
charge          = -1.0
maxnpart        = 1e2
pusher          = "Boris"

[species_2]
label           = "positron"
mass            = 1.0
charge          = 1.0
maxnpart        = 1e2
pusher          = "Boris"

[species_3]
label           = "ion"
mass            = 2.0
charge          = 1.0
maxnpart        = 1e2
pusher          = "Boris"

[species_4]
label           = "photon"
mass            = 0.0
charge          = 0.0
maxnpart        = 1e2
pusher          = "Photon"

[problem]

[visualization]
fields          = ["Bx", "By", "Bz", "Ex", "Ey", "Ez", "Jx", "Jy", "Jz", "density"]
fields_stride   = 4
