[simulation]
title   = "Reconnection"
runtime = 10000.0

[domain]
resolution = [256, 256]
# extent     = [-128.0, 128.0, -128.0, 128.0]
extent     = [-12.8, 12.8, -12.8, 12.8]
boundaries = ["PERIODIC", "PERIODIC"]

[algorithm]
CFL             = 0.9
correction      = 1.0
fieldsolver_ON  = true
deposit_ON      = true
current_filters = 8

[units]
ppc0       = 4.0
# larmor0    = 3.0
# skindepth0 = 3.0
larmor0    = 0.3
skindepth0 = 0.3

[particles]
n_species = 2

[species_1]
label    = "e-"
mass     = 1.0
charge   = -1.0
maxnpart = 200000000.0
pusher   = "BORIS"

[species_2]
label    = "e+"
mass     = 1.0
charge   = 1.0
maxnpart = 200000000.0
pusher   = "BORIS"

[problem]
# cs_width = 10.0
cs_width = 1.0

[visualization]
fields        = ["Bx", "By", "Bz", "Ex", "Ey", "Ez", "density"]
fields_stride = 2

[output]
format          = "hdf5"
interval        = 100
