[simulation]
title   = "Reconnection"
runtime = 2.0

[domain]
resolution = [1600, 2048]
extent     = [-0.5, 0.5, -0.64, 0.64]
boundaries = ["PERIODIC", "PERIODIC"]

[algorithm]
CFL             = 0.9
correction      = 1.0
fieldsolver_ON  = true
deposit_ON      = true
current_filters = 8

[units]
ppc0       = 4.0
larmor0    = 0.00125
skindepth0 = 0.00375

[particles]
n_species = 2

[species_1]
label    = "e-"
mass     = 1.0
charge   = -1.0
maxnpart = 1e8
pusher   = "BORIS"

[species_2]
label    = "e+"
mass     = 1.0
charge   = 1.0
maxnpart = 1e8
pusher   = "BORIS"

[problem]
cs_width = 0.000125

[visualization]
fields        = ["By", "density"]
fields_stride = 4

[output]
format   = "HDF5"
interval = 10
