[simulation]
title   = "Vacuum_monopole"
runtime = 0.1

[domain]
qsph_r0     = -100.0
qsph_h      = 0.001
sph_rabsorb = 9.0
resolution  = [256, 128]
extent      = [1.0, 10.0]
boundaries  = ["USER", "USER"]

[algorithm]
CFL        = 0.5
correction = 1.0

[units]
ppc0       = 10.0
larmor0    = 0.1
skindepth0 = 0.01

[problem]
spinup_time  = 0.25
omega_max    = 0.25

[visualization]
fields        = ["Br", "Btheta", "Bphi", "Er", "Etheta", "Ephi"]
fields_stride = 1
