[simulation]
title   = "Weibel-sprec"
runtime = 100.0

[domain]
resolution = [1024, 1024]
extent     = [-51.2, 51.2, -51.2, 51.2]
boundaries = ["PERIODIC", "PERIODIC"]

[algorithm]
CFL             = 0.5
correction      = 1.0
fieldsolver_ON  = true
deposit_ON      = true
current_filters = 25

[units]
ppc0       = 32.0
larmor0    = 1.0
skindepth0 = 1.0

[particles]
n_species = 4

[species_1]
label    = "e-_p"
mass     = 1.0
charge   = -1.0
maxnpart = 1e8
pusher   = "Boris"

[species_2]
label    = "e+_p"
mass     = 25.0
charge   = 1.0
maxnpart = 1e8
pusher   = "Boris"

[species_3]
label    = "e-_b"
mass     = 1.0
charge   = -1.0
maxnpart = 1e8
pusher   = "Boris"

[species_4]
label    = "e+_b"
mass     = 50.0
charge   = 1.0
maxnpart = 1e8
pusher   = "Boris"

[problem]
udrift_1 = -10.0
udrift_2 = -10.0
udrift_3 = 10.0
udrift_4 = 10.0

[visualization]
fields        = ["Bx", "By", "mass_density"]
fields_stride = 4

[output]
fields        = ["Bx", "By", "mass_density"]
format   = "HDF5"
interval = 100
