[simulation]
title   = "Discharge"
runtime = 100.0

[domain]
resolution = [5000]
extent     = [0.0, 100.0]   # extent of the domain in physical units
boundaries = [["PERIODIC"]]

[algorithm]
CFL             = 0.5
current_filters = 2

[units]
ppc0       = 64.0
larmor0    = 0.1  # fiducial larmor radius in physical units
skindepth0 = 0.1  # fiducial skin depth in physical units

[particles]
n_species = 2

[species_1]
label    = "e-"
mass     = 1.0
charge   = -1.0
maxnpart = 1e8

[species_2]
label    = "e+"
mass     = 1.0
charge   = 1.0
maxnpart = 1e8

[problem]
T        = 0.1
Rstar    = 1.0
contrast = 10.0
h        = 5.0

[output]
fields     = ["N_1", "N_2"]
particles  = ["X", "U"]
format     = "HDF5"
mom_smooth = 0

interval_time = 1.0 # output interval in time units

[diagnostics]
log_level = "WARNING"
