[simulation]
title   = "DischargePSR"
runtime = 0.5

[domain]
resolution = [1024, 1024]
extent     = [1.0, 20.0]   # extent of the domain in physical units
boundaries = [["CUSTOM", "ABSORB"], ["AXIS"]]
qsph_r0    = 0.0
qsph_h     = 0.0

[algorithm]
CFL             = 0.75
current_filters = 2

[units]
ppc0       = 32.0
larmor0    = 0.1  # fiducial larmor radius in physical units
skindepth0 = 1.0  # fiducial skin depth in physical units

[particles]
n_species = 2
use_weights = true

[species_1]
label    = "e-"
mass     = 1.0
charge   = -1.0
maxnpart = 1e8

[species_2]
label    = "e+"
mass     = 1.0
charge   = 1.0
maxnpart = 1e8

[problem]
T        = 0.1
Rstar    = 0.1
contrast = 10.0
h        = 0.1

[output]
fields     = ["N", "Nppc"]
particles  = ["X", "U"]
format     = "HDF5"
mom_smooth = 2

interval_time = 0.1 # output interval in time units

[diagnostics]
log_level = "DEBUG"
blocking_timers = true
