[simulation]
  name = "magnetar"
  engine = "srpic"
  runtime = 60.0

  # [simulation.domain]
  #   decomposition = [-1,2]

[grid]
  resolution = [4096,2048]
  extent = [[1.0, 400.0]]

  [grid.metric]
    metric = "qspherical"

  [grid.boundaries]
    fields = [["ATMOSPHERE", "ABSORB"]]
    particles = [["ATMOSPHERE", "ABSORB"]]
    
    [grid.boundaries.absorb]
      ds = 1.0

    [grid.boundaries.atmosphere]
      temperature = 0.1
      density = 40.0
      height = 0.02
      species = [1, 2]
      ds = 1.5
    
[scales]
  larmor0 = 5e-6
  skindepth0 = 0.01

[algorithms]
  current_filters = 4

  [algorithms.timestep]
    CFL = 0.5

  [algorithms.gca]
    e_ovr_b_max = 0.9
    larmor_max = 100.0

[particles]
  ppc0 = 4.0
  use_weights = true
  sort_interval = 100

  [[particles.species]]
  label = "e-"
  mass = 1.0
  charge = -1.0
  maxnpart = 1e8
  pusher = "Boris,GCA"

  [[particles.species]]
  label = "e+"
  mass = 1.0
  charge = 1.0
  maxnpart = 1e8
  pusher = "Boris,GCA"

 [[particles.species]]
  label = "e-"
  mass = 1.0
  charge = -1.0
  maxnpart = 1e4
  pusher = "Boris,GCA"

  [[particles.species]]
  label = "e+"
  mass = 1.0
  charge = 1.0
  maxnpart = 1e4
  pusher = "Boris,GCA"

 [[particles.species]]
  label = "e-"
  mass = 1.0
  charge = -1.0
  maxnpart = 2e8
  pusher = "Boris,GCA"

  [[particles.species]]
  label = "e+"
  mass = 1.0
  charge = 1.0
  maxnpart = 2e8
  pusher = "Boris,GCA"

[setup]
  Bsurf = 1.0
  omega = 0.0125
  
[output]
  fields = ["N_1", "N_2", "E", "B"]
  format = "hdf5"
  interval_time = 0.1

[diagnostics]
  interval = 10
