[Plot.0]
field_selected = 4
cmap = "BrBG"
vmax = 0.05217
symmetric = true
autoscale = false
vmin = -0.05217
log = false
type = "Pcolor2d"
ID = 0

[Plot.1]
field_selected = 5
cmap = "BrBG"
vmax = 0.066
symmetric = true
autoscale = false
vmin = -0.066
log = false
type = "Pcolor2d"
ID = 1

[Plot.2]
field_selected = 3
cmap = "BrBG"
vmax = 0.03712
symmetric = true
autoscale = false
vmin = -0.03712
log = false
type = "Pcolor2d"
ID = 2

[Plot.3]
field_selected = 0
cmap = "RdBu"
vmax = 0.2394
symmetric = true
autoscale = false
vmin = -0.2394
log = false
type = "Pcolor2d"
ID = 3

[Plot.4]
field_selected = 8
cmap = "Hot"
vmax = 13.54
symmetric = false
autoscale = false
vmin = 0.0
log = false
type = "Pcolor2d"
ID = 4

[Plot.5]
field_selected = 6
cmap = "PiYG"
vmax = 2.366
symmetric = true
autoscale = false
vmin = -2.366
log = false
type = "Pcolor2d"
ID = 5

[Plot]
npanels = 6
outline_color = [1.000, 1.000, 1.000, 1.000]
range = [-2.894, 14.316, -8.952, 6.305]
collapsed_controls = false
