[simulation]
  name = "magnetosphere"
  engine = "srpic"
  runtime = 10.0

[grid]
  resolution = [512, 256]
  extent = [[1.0, 10.0]]

  [grid.metric]
    metric = "spherical"

  [grid.boundaries]
    fields = [["ATMOSPHERE", "ABSORB"]]
    particles = [["ATMOSPHERE", "ABSORB"]]
    
    [grid.boundaries.absorb]
      ds = 1.0

    [grid.boundaries.atmosphere]
      temperature = 0.1
      density = 4.0
      height = 0.05
      species = [1, 2]
    
[scales]
  larmor0 = 0.1
  skindepth0 = 0.01

[algorithms]
  current_filters = 4

  [algorithms.timestep]
    CFL = 0.5

[particles]
  ppc0 = 10.0

  [[particles.species]]
  label = "e-"
  mass = 1.0
  charge = -1.0
  maxnpart = 1e6

  [[particles.species]]
  label = "e+"
  mass = 1.0
  charge = 1.0
  maxnpart = 1e6

[setup]
  Bsurf = 1.0
  period = 10.0
  
[output]
  fields = ["N_1", "N_2", "E", "B"]
  format = "hdf5"
  interval_time = 0.1
