name: Unit tests

on:
  pull_request:
    branches:
      - master

jobs:
  tests:
    strategy:
      matrix:
        cuda: ["ON", "OFF"]
        precision: ["double", "single"]
    runs-on:
      - self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0
      - name: Compile
        run: |
          cmake -B build -D Kokkos_ENABLE_CUDA=${{ matrix.cuda }} -D TESTS=ON -D precision=${{ matrix.precision }}
          cd build
          make -j
      - name: Run tests
        run: |
          cd build/tests
          ctest -j
