name: Compilation

on:
  pull_request:
    branches:
      - master

jobs:
  build-pic:
    strategy:
      matrix:
        include:
          - pgen: "weibel"
            metric: "minkowski"
          - pgen: "magnetosphere"
            metric: "qspherical"
          - pgen: "magnetosphere"
            metric: "spherical"

    runs-on:
      - self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0
      - name: Compile
        run: |
          cmake -B build -D pgen=${{ matrix.pgen }} -D metric=${{ matrix.metric }} -D Kokkos_ENABLE_CUDA=ON
          cd build
          make -j

  build-grpic:
    strategy:
      matrix:
        include:
          - pgen: "wald"
            metric: "kerr_schild"
          - pgen: "wald"
            metric: "qkerr_schild"

    runs-on:
      - self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0
      - name: Compile
        run: |
          cmake -B build -D engine=grpic -D pgen=${{ matrix.pgen }} -D metric=${{ matrix.metric }} -D Kokkos_ENABLE_CUDA=ON
          cd build
          make -j
